[
  {
    "ClassName": "System.ApplicationException",
    "Message": "Testing the exception handling.",
    "Data": null,
    "HelpURL": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146232832,
    "Source": "Xdxd.DotNet.Rpc.Tests",
    "WatsonBuckets": null
  }
]